import sys
import os
import pytest

# Ensure backend/ is on the path so all backend imports resolve correctly
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from app import create_app
from extensions import db, limiter
from routes.solo import (
    construct_game,
    apply_move,
    NUM_ROWS,
    NUM_COLS,
)
from utils.game import DeterministicRNG, construct_grid, SPACE


# ---------------------------------------------------------------------------
# Pre-verified game data from README
# Each entry is {"seed": str, "moves": list[str]}
# ---------------------------------------------------------------------------

WON_GAME_1 = {
  "seed": "9b4bfe0f-e639-4772-8a40-a5b1f59b5abd",
  "moves": [
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "up",
    "left",
    "up",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "down",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "down",
    "right",
    "down",
    "left",
    "up",
    "down",
    "right",
    "down",
    "left",
    "up",
    "down",
    "right",
    "left",
    "up",
    "down",
    "right",
    "left",
    "up",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "up",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "right",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "right",
    "down",
    "right",
    "up",
    "left",
    "up",
    "down",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "right",
    "down",
    "left",
    "up",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "left",
    "right",
    "left",
    "right",
    "left",
    "right",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "left",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "down",
    "up",
    "left",
    "up",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "up",
    "left",
    "right",
    "up",
    "down",
    "up",
    "left",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "up",
    "down",
    "down",
    "down",
    "down",
    "down",
    "right",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "right",
    "down",
    "left",
    "right",
    "right",
    "up",
    "left",
    "down",
    "left",
    "right",
    "left",
    "right",
    "down",
    "right",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "right",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "left",
    "up",
    "left",
    "down",
    "left",
    "up",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "right",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "left",
    "down",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "right",
    "left",
    "up",
    "right",
    "up",
    "up",
    "up",
    "down",
    "left",
    "up",
    "right",
    "up",
    "right",
    "right",
    "right",
    "up",
    "up",
    "up",
    "right",
    "up",
    "up",
    "right",
    "right",
    "up",
    "right",
    "up",
    "right",
    "up",
    "right",
    "right",
    "left",
    "right",
    "up",
    "left",
    "up",
    "right",
    "right",
    "right",
    "up",
    "right",
    "up",
    "right",
    "right",
    "right",
    "right",
    "right",
    "left",
    "up",
    "up",
    "up",
    "up",
    "up",
    "up",
    "up",
    "right",
    "down",
    "up",
    "right",
    "up",
    "up",
    "right",
    "right",
    "right",
    "right",
    "right",
    "up",
  ]
}


WON_GAME_2 = {
    "seed": "a223dba4-255a-4659-9228-161d2604e4d6",
    "moves": ["left","up","right","left","down","left","right","left","right","left","right","up","down","left","up","left","right","down","left","up","right","down","left","up","right","down","left","up","up","down","right","down","left","up","down","right","down","left","up","right","down","left","up","left","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","down","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","left","right","left","right","up","down","down","left","up","right","down","left","right","up","down","left","up","right","down","right","left","up","up","down","left","right","up","down","left","right","down","up","left","up","right","left","right","up","down","up","left","down","up","down","left","right","down","right","right","up"],
}

LOST_GAME_1 = {
  "seed": "66e2f11d-83df-4b05-a3c0-ddda9164194f",
  "moves": [
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "left",
    "left",
    "left",
    "up",
    "up",
    "up",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "up",
    "up",
    "up",
    "up",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "right",
    "up",
    "up",
    "up",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "up",
    "up",
    "up",
    "up",
    "up",
    "down",
    "down",
    "down",
    "up",
    "up",
    "up",
    "right",
    "right",
    "right",
    "right",
    "left",
    "left",
    "up",
    "up",
    "up",
    "up",
    "up",
    "up",
    "up",
    "up",
    "up",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "right",
    "up",
    "up"
  ]
}

LOST_GAME_2 = {
    "seed": "7a9c52bc-c56e-4443-a0cd-7d6a94280753",
    "moves": ["left","left","left","left","left","left","left","left","left","left","left","left","left","left","right","right","right","right","right","right","right","right","right","left","left","up","down","down","down","down","down","down","down","right","right","left","left","up","up","up","up","up","up","up","up","up","up","up","left","right","right","right","right","left","up","up","up","down","right","left","left","left","left","left","left","left","left","up","down","up","down","down","right","left","right","down","left","up","right","left","down","down","up","up","down","up","down","up","up","down","up","down","up","left","right","up","left","down","right","up","left","down","right","up","left","left","left","left","left","left","left","left","left","left","left","right","right","right","right","right","right","right","right","right","right","left","left","left","up","down","down","down","down","down","down","down","down","down","down","up","up","up","left","right","right","right","right","left","left","up","up","up","up","up","up","up","up","up","up","up","up","up","up","left","right","right","left","left","left","down","up","down","down","down","down","right","right","left","left","up","right","down","right","left","down","down"],
}

ABANDONED_GAME_1 = {
    "seed": "68f492cd-26ec-4e92-95f6-219cd79beffc",
    "moves": ["up", "down", "left", "right", "up"],
}

ABANDONED_GAME_2 = {
    "seed": "9f241cb8-55a8-498a-aee0-a39f1523abd4",
    "moves": ["left", "up", "right", "down", "up"],
}

INVAILD_GAME_1 = {
    "seed": "694193c2-8533-4a91-93db-d37602191c56",
    "moves": ["left","left","left","left","left","left","left","left","left","left", "left", "left", "right", "up"],
}

INVAILD_GAME_2 = {
    "seed": "41bee31d-9a36-41fb-8891-5b974b1d1793",
    "moves": ["right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right","right", "right"],
}


# ---------------------------------------------------------------------------
# build_replay — module-level helper
#
# Drives the game engine forward from the given seed using the same logic as
# simulate_game, applying the first valid direction from the priority list and
# recording every move made.
#
# Parameters
# ----------
# seed        : seed passed to DeterministicRNG (string or any type)
# target_state: one of "Won", "Lost", "In Progress" — stop when reached
# exact_moves : if set, stop after exactly this many valid moves (ignores
#               target_state)
#
# Returns {"seed": seed, "moves": [...]}
# ---------------------------------------------------------------------------

def build_replay(seed, target_state=None, exact_moves=None):
    rng = DeterministicRNG(str(seed))
    game = construct_game(construct_grid(NUM_ROWS, NUM_COLS, SPACE), rng)
    game.generate_tiles()

    moves = []
    directions = ["up", "down", "left", "right"]

    if exact_moves is not None:
        count = 0
        while count < exact_moves:
            valid = set(game.get_valid_moves())
            moved = False
            for d in directions:
                if d in valid:
                    apply_move(game, d)
                    game.generate_tiles()
                    moves.append(d)
                    count += 1
                    moved = True
                    break
            if not moved:
                break
        return {"seed": seed, "moves": moves}

    if target_state is None:
        raise ValueError("Either target_state or exact_moves must be provided")

    max_iterations = 10_000
    for _ in range(max_iterations):
        state = game.get_state()
        if state == target_state:
            return {"seed": seed, "moves": moves}
        if state != "In Progress":
            break
        valid = set(game.get_valid_moves())
        if not valid:
            break
        for d in directions:
            if d in valid:
                apply_move(game, d)
                game.generate_tiles()
                moves.append(d)
                break

    if game.get_state() == target_state:
        return {"seed": seed, "moves": moves}

    raise RuntimeError(
        f"build_replay: could not reach state '{target_state}' from seed '{seed}' "
        f"within {max_iterations} iterations (ended in '{game.get_state()}')"
    )


# ---------------------------------------------------------------------------
# Core fixtures
# ---------------------------------------------------------------------------

@pytest.fixture
def app():
    flask_app = create_app({
        "TESTING": True,
        "SQLALCHEMY_DATABASE_URI": "sqlite:///:memory:",
        "SECRET_KEY": "test-secret-key",
        "WTF_CSRF_ENABLED": False,
    })
    with flask_app.app_context():
        db.create_all()
        yield flask_app
        db.drop_all()


@pytest.fixture
def client(app):
    with app.test_client() as c:
        with app.app_context():
            yield c


@pytest.fixture
def db_session(app):
    with app.app_context():
        yield db


@pytest.fixture
def seeded_client(client, app):
    with app.app_context():
        res = client.get("/api/statistics")
        assert res.status_code == 200
        user_id = res.get_json()["user_id"]
    return client, user_id


@pytest.fixture
def limiter_client(app):
    limiter.init_app(app)
    with app.test_client() as c:
        with app.app_context():
            yield c


# ---------------------------------------------------------------------------
# Replay fixtures — use pre-verified game data from README
# ---------------------------------------------------------------------------

@pytest.fixture
def won_replay():
    return WON_GAME_1


@pytest.fixture
def lost_replay():
    return LOST_GAME_1


@pytest.fixture
def in_progress_replay():
    # First 5 moves of a known game — always in-progress at move 5
    game_data = ABANDONED_GAME_1
    return {"seed": game_data["seed"], "moves": game_data["moves"][:5]}
