#!/usr/bin/env python3
"""
Divergence diagnostic — Python side.

1. Run with default settings to get per-step sums:
       python3 divergence_diagnostic.py > py_steps.txt

2. Compare with the JS output:
       node divergence_diagnostic.mjs > js_steps.txt
       diff py_steps.txt js_steps.txt

3. Set BREAK_INDEX to the first differing step for a detailed snapshot.

Output format (one line per step, machine-diffable):
    step|dir|sum_after_move|sum_after_spawn|rng_state_after_spawn
"""
import sys
import copy

sys.path.insert(0, "backend")
from utils.game import DeterministicRNG, Game, SPACE, ADDITION, SUBTRACTION, construct_grid

# ── Configure ─────────────────────────────────────────────────────────────────
{
  "seed": "9b4bfe0f-e639-4772-8a40-a5b1f59b5abd",
  "moves": [
    "left",
    "left",
    "left",
    "left",
    "left",
    "left",
    "up",
    "left",
    "up",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "down",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "down",
    "right",
    "down",
    "left",
    "up",
    "down",
    "right",
    "down",
    "left",
    "up",
    "down",
    "right",
    "left",
    "up",
    "down",
    "right",
    "left",
    "up",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "up",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "right",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "right",
    "down",
    "right",
    "up",
    "left",
    "up",
    "down",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "right",
    "down",
    "left",
    "up",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "left",
    "right",
    "left",
    "right",
    "left",
    "right",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "left",
    "down",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "down",
    "up",
    "left",
    "up",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "right",
    "left",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "up",
    "left",
    "right",
    "up",
    "down",
    "up",
    "left",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "up",
    "down",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "up",
    "down",
    "down",
    "down",
    "down",
    "down",
    "right",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "right",
    "down",
    "left",
    "right",
    "right",
    "up",
    "left",
    "down",
    "left",
    "right",
    "left",
    "right",
    "down",
    "right",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "right",
    "right",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "left",
    "up",
    "left",
    "down",
    "left",
    "up",
    "left",
    "up",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "down",
    "right",
    "down",
    "up",
    "right",
    "down",
    "left",
    "up",
    "left",
    "down",
    "right",
    "down",
    "left",
    "up",
    "right",
    "down",
    "left",
    "down",
    "right",
    "left",
    "up",
    "right",
    "up",
    "up",
    "up",
    "down",
    "left",
    "up",
    "right",
    "up",
    "right",
    "right",
    "right",
    "up",
    "up",
    "up",
    "right",
    "up",
    "up",
    "right",
    "right",
    "up",
    "right",
    "up",
    "right",
    "up",
    "right",
    "right",
    "left",
    "right",
    "up",
    "left",
    "up",
    "right",
    "right",
    "right",
    "up",
    "right",
    "up",
    "right",
    "right",
    "right",
    "right",
    "right",
    "left",
    "up",
    "up",
    "up",
    "up",
    "up",
    "up",
    "up",
    "right",
    "down",
    "up",
    "right",
    "up",
    "up",
    "right",
    "right",
    "right",
    "right",
    "right",
    "up"
  ]
}
SEED  = "47901452-df64-40c5-beb7-417249808f3f"         # e.g. "c52cb2e1-3982-4ab3-988c-523d1f52c6e9"
MOVES = ["left","up","left","left","left","up","left","up","down","up","left","left","up","left","up","right","down","left","up","down","right","down","left","down","up","down","right","left","up","down","right","down","left","up","right","down","down","left","up","right","down","down","left","up","left","down","up","left","down","up","right","down","left","down","up","right","down","left","up","down","left","up","down","left","up","right","left","down","up","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","right","down","left","up","right","down","up","left","left","up","up","up","up","up","up","up","up","up","left","down","left","right","left","up","left","right","up","up","up","left","up","up","right","down","up","left","right","left","up","down","left","right","down","left","right","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","left","up","right","down","down","down","right","left","up","right","down","left","up","right","down","left"]
BREAK_INDEX = None  # set to an int to print a detailed snapshot at that step index
# ─────────────────────────────────────────────────────────────────────────────

NUM_ROWS  = 6
NUM_COLS  = 7
OPS       = [ADDITION, SUBTRACTION]
OP_RATE   = 0.67
DIGITS    = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
TILES_PER = 2
OPERATORS = set(OPS)


def board_sum(grid: list) -> int:
    total = 0
    for row in grid:
        for cell in row:
            if cell != SPACE and cell not in OPERATORS:
                total += int(cell)
    return total


def print_grid(grid: list, label: str = "") -> None:
    if label:
        print(f"  [{label}]")
    for row in grid:
        print("  " + " ".join(f"{str(c):>5}" for c in row))
    print()


def rng_state(rng: DeterministicRNG) -> str:
    return f"0x{rng._state:08x}"


def snapshot(step: int, direction: str,
             before_move, after_move, after_spawn) -> None:
    print()
    print(f"╔══ SNAPSHOT  step={step}  dir={direction} ══╗")
    print_grid(before_move, "board before move")
    print_grid(after_move,  "board after move (before spawn)")
    print_grid(after_spawn, "board after spawn")

    spawned = []
    for r in range(NUM_ROWS):
        for c in range(NUM_COLS):
            if after_move[r][c] == SPACE and after_spawn[r][c] != SPACE:
                spawned.append((r, c, after_spawn[r][c]))
    print(f"  Spawned tiles : {spawned}")

    moved_cells = []
    for r in range(NUM_ROWS):
        for c in range(NUM_COLS):
            if before_move[r][c] != after_move[r][c]:
                moved_cells.append((r, c, before_move[r][c], "→", after_move[r][c]))
    print(f"  Changed cells : {moved_cells}")
    print()


# ── Main ──────────────────────────────────────────────────────────────────────
rng  = DeterministicRNG(str(SEED))
game = Game(
    construct_grid(NUM_ROWS, NUM_COLS, SPACE),
    rng,
    NUM_ROWS, NUM_COLS,
    OPS, OP_RATE, DIGITS, TILES_PER,
)
game.generate_tiles()

print(f"seed={SEED}")
print(f"init_sum={board_sum(game.get_game())}  init_rng={rng_state(rng)}")
print()
print("step|dir|sum_after_move|sum_after_spawn|rng_state_after_spawn")

for i, move in enumerate(MOVES):
    grid_before_move = copy.deepcopy(game.get_game())

    if   move == "up":    game.slide_up()
    elif move == "down":  game.slide_down()
    elif move == "left":  game.slide_left()
    elif move == "right": game.slide_right()
    else:
        print(f"UNKNOWN MOVE at step {i}: {move!r}", file=sys.stderr)
        sys.exit(1)

    sum_after_move  = board_sum(game.get_game())
    grid_after_move = copy.deepcopy(game.get_game())

    game.generate_tiles()

    sum_after_spawn  = board_sum(game.get_game())
    grid_after_spawn = copy.deepcopy(game.get_game())
    state_hex        = rng_state(rng)

    print(f"{i}|{move}|{sum_after_move}|{sum_after_spawn}|{state_hex}")

    if BREAK_INDEX is not None and i == BREAK_INDEX:
        snapshot(i, move, grid_before_move, grid_after_move, grid_after_spawn)
        break

print()
print(f"final_state={game.get_state()}")
print(f"Is Won: {game.is_won()}")
print(f"Max Tile: {max([cell for row in game.get_game() for cell in row if isinstance(cell, int)])}")
